// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChOlKonPUXzvN2_UaRgujx5pnh7qyQH0c',
    appId: '1:352036931719:web:f40224865aa61353721022',
    messagingSenderId: '352036931719',
    projectId: 'empowered-ed9ae',
    authDomain: 'empowered-ed9ae.firebaseapp.com',
    storageBucket: 'empowered-ed9ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTeyq6Wzxc283tLAPFzMfTYZRDdYVxKI',
    appId: '1:352036931719:android:693d5653a71c2df4721022',
    messagingSenderId: '352036931719',
    projectId: 'empowered-ed9ae',
    storageBucket: 'empowered-ed9ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-ZV4IS8w2VxQcb5o9mTLQ0bNm4MxE3s',
    appId: '1:352036931719:ios:e9c3464cae1097ef721022',
    messagingSenderId: '352036931719',
    projectId: 'empowered-ed9ae',
    storageBucket: 'empowered-ed9ae.appspot.com',
    iosBundleId: 'com.cyborgs.empoweredTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1-ZV4IS8w2VxQcb5o9mTLQ0bNm4MxE3s',
    appId: '1:352036931719:ios:e9c3464cae1097ef721022',
    messagingSenderId: '352036931719',
    projectId: 'empowered-ed9ae',
    storageBucket: 'empowered-ed9ae.appspot.com',
    iosBundleId: 'com.cyborgs.empoweredTeacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChOlKonPUXzvN2_UaRgujx5pnh7qyQH0c',
    appId: '1:352036931719:web:f40224865aa61353721022',
    messagingSenderId: '352036931719',
    projectId: 'empowered-ed9ae',
    authDomain: 'empowered-ed9ae.firebaseapp.com',
    storageBucket: 'empowered-ed9ae.appspot.com',
  );
}